export {default as Home} from "./home"
export {default as AddPost} from "./AddPost"
export {default as AllPosts} from "./AllPosts"
export {default as EditPost} from "./EditPost"
export {default as Login} from "./Login"
export {default as Post} from "./Post"
export {default as SignUp} from "./SignUp"
